# Generated by Django 3.2.4 on 2021-06-30 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=30)),
                ('decription', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 30, 17, 25, 51, 402074))),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
